### PR TITLE
Added the changes to ready the code to submit a PR

### PR DESCRIPTION
**Pull request by gonzalorey**

### CODE REVIEW

**Comment by restorandodeploy** [comment]
By analyzing the blame information on this pull request, we identified @grosser, @jonmoter and @henders to be potential reviewers

**Comment by grosser** [comment]
cute bot ;D

**Comment by henders** [comment]
lol, totally! :)

**Comment by gschammah** [comment]
@henders @grosser https://github.com/facebook/mention-bot :)

**Comment by jbarreneche** [comment]
@gonzalorey Anything else missing to make the PR to zendesk?

**Comment by gonzalorey** [comment]
Nop, it's ready to go 💃

**Comment by jbarreneche** [comment]
great! then merge it and let me know if you need help writting the PR to zendesk

**Pull request merged**
